version: "3.9"
services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    image: stayfi-web:dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # For dev iterations, you can mount source and run dev script instead of standalone
    # volumes:
    #   - ./apps/web:/app
    # command: npm run dev

